//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušení výpůjčky.
        /// </summary>
        public static string EmailType_RentingCalcelation {
            get {
                return ResourceManager.GetString("EmailType_RentingCalcelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna výpůjčky.
        /// </summary>
        public static string EmailType_RentingEdit {
            get {
                return ResourceManager.GetString("EmailType_RentingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění na konec výpůjčky.
        /// </summary>
        public static string EmailType_RentingEndsReminder {
            get {
                return ResourceManager.GetString("EmailType_RentingEndsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová výpůjčka.
        /// </summary>
        public static string EmailType_RentingNew {
            get {
                return ResourceManager.GetString("EmailType_RentingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NENAVRÁCENÁ VÝPŮJČKA!!.
        /// </summary>
        public static string EmailType_RentingNotReturned {
            get {
                return ResourceManager.GetString("EmailType_RentingNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušeno.
        /// </summary>
        public static string RentalState_Canceled {
            get {
                return ResourceManager.GetString("RentalState_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapůjčeno.
        /// </summary>
        public static string RentalState_Lended {
            get {
                return ResourceManager.GetString("RentalState_Lended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezapůjčeno.
        /// </summary>
        public static string RentalState_NotLended {
            get {
                return ResourceManager.GetString("RentalState_NotLended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vráceno.
        /// </summary>
        public static string RentalState_Returned {
            get {
                return ResourceManager.GetString("RentalState_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string RoleType_Administrator {
            get {
                return ResourceManager.GetString("RoleType_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník.
        /// </summary>
        public static string RoleType_Customer {
            get {
                return ResourceManager.GetString("RoleType_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaměstnanec.
        /// </summary>
        public static string RoleType_Employee {
            get {
                return ResourceManager.GetString("RoleType_Employee", resourceCulture);
            }
        }
    }
}
