//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Web.Localization.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendář.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhající výpůjka.
        /// </summary>
        public static string Calendar_Lended {
            get {
                return ResourceManager.GetString("Calendar_Lended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádná třída.
        /// </summary>
        public static string Calendar_NoClass {
            get {
                return ResourceManager.GetString("Calendar_NoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatím nevypůjčená výpůjčka.
        /// </summary>
        public static string Calendar_NotLended {
            get {
                return ResourceManager.GetString("Calendar_NotLended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato výpůjčka měla být navrácena.
        /// </summary>
        public static string Calendar_NotReturned {
            get {
                return ResourceManager.GetString("Calendar_NotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navrácená výpůjčka.
        /// </summary>
        public static string Calendar_Returned {
            get {
                return ResourceManager.GetString("Calendar_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazníci.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Třida.
        /// </summary>
        public static string Customers_Class {
            get {
                return ResourceManager.GetString("Customers_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Customers_Email {
            get {
                return ResourceManager.GetString("Customers_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Customers_Name {
            get {
                return ResourceManager.GetString("Customers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte žádné zákazníky.
        /// </summary>
        public static string Customers_NoCustomers {
            get {
                return ResourceManager.GetString("Customers_NoCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazníkovy výpůjčky.
        /// </summary>
        public static string Customers_Rentings {
            get {
                return ResourceManager.GetString("Customers_Rentings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaměstnanci.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaměstnanci.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivní pozvánky.
        /// </summary>
        public static string Employees_ActiveLinks {
            get {
                return ResourceManager.GetString("Employees_ActiveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka nemůže mít splatnost v minulosti.
        /// </summary>
        public static string Employees_CantBeInPast {
            get {
                return ResourceManager.GetString("Employees_CantBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Employees_Email {
            get {
                return ResourceManager.GetString("Employees_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platná do.
        /// </summary>
        public static string Employees_LinkExpiration {
            get {
                return ResourceManager.GetString("Employees_LinkExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka pro.
        /// </summary>
        public static string Employees_LinkFor {
            get {
                return ResourceManager.GetString("Employees_LinkFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro role.
        /// </summary>
        public static string Employees_LinkForRoles {
            get {
                return ResourceManager.GetString("Employees_LinkForRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka musí být buř pro zaměstance, nebo admina, nebo oba.
        /// </summary>
        public static string Employees_MustHaveRole {
            get {
                return ResourceManager.GetString("Employees_MustHaveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Employees_Name {
            get {
                return ResourceManager.GetString("Employees_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová pozvánka.
        /// </summary>
        public static string Employees_NewInvite {
            get {
                return ResourceManager.GetString("Employees_NewInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyly nalezeny žádné aktivní pozvánky.
        /// </summary>
        public static string Employees_NoActiveLinks {
            get {
                return ResourceManager.GetString("Employees_NoActiveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat admina.
        /// </summary>
        public static string Employees_RemoveAdmin {
            get {
                return ResourceManager.GetString("Employees_RemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat zaměstance.
        /// </summary>
        public static string Employees_RemoveEmployee {
            get {
                return ResourceManager.GetString("Employees_RemoveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Employees_Roles {
            get {
                return ResourceManager.GetString("Employees_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bude admin.
        /// </summary>
        public static string Employees_WillBeAdmin {
            get {
                return ResourceManager.GetString("Employees_WillBeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bude zaměstnanec.
        /// </summary>
        public static string Employees_WillBeEmployee {
            get {
                return ResourceManager.GetString("Employees_WillBeEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historie.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnít popisek předmětu.
        /// </summary>
        public static string History_ChangeDescription {
            get {
                return ResourceManager.GetString("History_ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co se stalo.
        /// </summary>
        public static string History_Content {
            get {
                return ResourceManager.GetString("History_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník.
        /// </summary>
        public static string History_Customer {
            get {
                return ResourceManager.GetString("History_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník nesedí s rezervací..
        /// </summary>
        public static string History_InvalidCustomer {
            get {
                return ResourceManager.GetString("History_InvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět.
        /// </summary>
        public static string History_Item {
            get {
                return ResourceManager.GetString("History_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový záznam do historie.
        /// </summary>
        public static string History_New {
            get {
                return ResourceManager.GetString("History_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový popisek.
        /// </summary>
        public static string History_NewDescription {
            get {
                return ResourceManager.GetString("History_NewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat záznam.
        /// </summary>
        public static string History_NewRecord {
            get {
                return ResourceManager.GetString("History_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záznam.
        /// </summary>
        public static string History_Record {
            get {
                return ResourceManager.GetString("History_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        public static string History_Time {
            get {
                return ResourceManager.GetString("History_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předměty.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příslušenství.
        /// </summary>
        public static string Item_Accessories {
            get {
                return ResourceManager.GetString("Item_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příslušenství k.
        /// </summary>
        public static string Item_AccessoryTo {
            get {
                return ResourceManager.GetString("Item_AccessoryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat příslušenství.
        /// </summary>
        public static string Item_AddAccessory {
            get {
                return ResourceManager.GetString("Item_AddAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit a přidat předmět.
        /// </summary>
        public static string Item_AddItem {
            get {
                return ResourceManager.GetString("Item_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový.
        /// </summary>
        public static string Item_AddNew {
            get {
                return ResourceManager.GetString("Item_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit všechny obrázky.
        /// </summary>
        public static string Item_ChangeAllImages {
            get {
                return ResourceManager.GetString("Item_ChangeAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat příslušenství.
        /// </summary>
        public static string Item_ChooseAccessory {
            get {
                return ResourceManager.GetString("Item_ChooseAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat příslušenství k.
        /// </summary>
        public static string Item_ChooseAccessoryTo {
            get {
                return ResourceManager.GetString("Item_ChooseAccessoryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhledový obrázek.
        /// </summary>
        public static string Item_CoverImage {
            get {
                return ResourceManager.GetString("Item_CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit typ.
        /// </summary>
        public static string Item_Create {
            get {
                return ResourceManager.GetString("Item_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat předmět &quot;{0}&quot;.
        /// </summary>
        public static string Item_DeleteMessage {
            get {
                return ResourceManager.GetString("Item_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisek.
        /// </summary>
        public static string Item_Description {
            get {
                return ResourceManager.GetString("Item_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail předmětu {0}.
        /// </summary>
        public static string Item_Detail {
            get {
                return ResourceManager.GetString("Item_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některé předměty jsou označeny zárověň jako příslušenství a příslušenství k.
        /// </summary>
        public static string Item_DuplicateAccessory {
            get {
                return ResourceManager.GetString("Item_DuplicateAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace předmětu - {0}.
        /// </summary>
        public static string Item_Edit {
            get {
                return ResourceManager.GetString("Item_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek úspěšně změněn.
        /// </summary>
        public static string Item_FileChanged {
            get {
                return ResourceManager.GetString("Item_FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát soubor.
        /// </summary>
        public static string Item_FileUpload {
            get {
                return ResourceManager.GetString("Item_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor úspěšně nahrán.
        /// </summary>
        public static string Item_FileUploaded {
            get {
                return ResourceManager.GetString("Item_FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor se nepodařilo nahrát, zkotrolujte zda nahráváte obrázek a zkuste to znovu..
        /// </summary>
        public static string Item_FileUploadFailed {
            get {
                return ResourceManager.GetString("Item_FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam fyzických předmětů.
        /// </summary>
        public static string Item_ListOfItems {
            get {
                return ResourceManager.GetString("Item_ListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název předmětu.
        /// </summary>
        public static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Item_Note {
            get {
                return ResourceManager.GetString("Item_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet předmětů: {0}.
        /// </summary>
        public static string Item_NumberOfItems {
            get {
                return ResourceManager.GetString("Item_NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet předmětů.
        /// </summary>
        public static string Item_NumberOfItemsLabel {
            get {
                return ResourceManager.GetString("Item_NumberOfItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled předmětů.
        /// </summary>
        public static string Item_Overview {
            get {
                return ResourceManager.GetString("Item_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu {0} už není příslušenství ?.
        /// </summary>
        public static string Item_RemoveAccessory {
            get {
                return ResourceManager.GetString("Item_RemoveAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dva nebo více předmětů nemůže mít stejné unikatní identifikátory.
        /// </summary>
        public static string Item_SameUniqueIdentifiers1 {
            get {
                return ResourceManager.GetString("Item_SameUniqueIdentifiers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikátní klíč &quot;{0}&quot; nemůže být použit, protože již náleží jinému předmětu.
        /// </summary>
        public static string Item_SameUniqueIdentifiers2 {
            get {
                return ResourceManager.GetString("Item_SameUniqueIdentifiers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typy předmětů.
        /// </summary>
        public static string Item_Type {
            get {
                return ResourceManager.GetString("Item_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikátní identifikátor.
        /// </summary>
        public static string Item_UniqueIdentifier {
            get {
                return ResourceManager.GetString("Item_UniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávné přihlašovací jméno nebo heslo..
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamatovat si mě?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít místní přihlášení.
        /// </summary>
        public static string Login_UseAdminAccount {
            get {
                return ResourceManager.GetString("Login_UseAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít externí služby.
        /// </summary>
        public static string Login_UseExternalLogin {
            get {
                return ResourceManager.GetString("Login_UseExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení z administrativy proběhlo úspěšně..
        /// </summary>
        public static string Logout_Succesful {
            get {
                return ResourceManager.GetString("Logout_Succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Půjčovna.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše půjčovna se nachází zde:.
        /// </summary>
        public static string Rental_Address {
            get {
                return ResourceManager.GetString("Rental_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string Rental_City {
            get {
                return ResourceManager.GetString("Rental_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace půjčovny.
        /// </summary>
        public static string Rental_Edit {
            get {
                return ResourceManager.GetString("Rental_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavírá.
        /// </summary>
        public static string Rental_EndsAt {
            get {
                return ResourceManager.GetString("Rental_EndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimální časový úsek pro výpůjčku (v minutách).
        /// </summary>
        public static string Rental_MinTimeUnit {
            get {
                return ResourceManager.GetString("Rental_MinTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název půjčovny.
        /// </summary>
        public static string Rental_Name {
            get {
                return ResourceManager.GetString("Rental_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemůžete zavírat dříve než otvíráte.
        /// </summary>
        public static string Rental_OpeningHoursError {
            get {
                return ResourceManager.GetString("Rental_OpeningHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevírá.
        /// </summary>
        public static string Rental_StartsAt {
            get {
                return ResourceManager.GetString("Rental_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Rental_Street {
            get {
                return ResourceManager.GetString("Rental_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string Rental_ZipCode {
            get {
                return ResourceManager.GetString("Rental_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete tudo výpůjčku zrušit ?.
        /// </summary>
        public static string Renting_Cancel {
            get {
                return ResourceManager.GetString("Renting_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže být posunuta do minulosti.
        /// </summary>
        public static string Renting_CannotBeSetInPast {
            get {
                return ResourceManager.GetString("Renting_CannotBeSetInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat předměty.
        /// </summary>
        public static string Renting_ChooseItems {
            get {
                return ResourceManager.GetString("Renting_ChooseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová výpůjčka.
        /// </summary>
        public static string Renting_Create {
            get {
                return ResourceManager.GetString("Renting_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže být v minulosti.
        /// </summary>
        public static string Renting_DateInPast {
            get {
                return ResourceManager.GetString("Renting_DateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail výpůjčky.
        /// </summary>
        public static string Renting_Detail {
            get {
                return ResourceManager.GetString("Renting_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace výpůjčky.
        /// </summary>
        public static string Renting_Edit {
            get {
                return ResourceManager.GetString("Renting_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec výpůjčky.
        /// </summary>
        public static string Renting_EndsAt {
            get {
                return ResourceManager.GetString("Renting_EndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec výpůjčky musí být v pracovní době..
        /// </summary>
        public static string Renting_EndsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_EndsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže končit v minulosti, pokud není vrácena..
        /// </summary>
        public static string Renting_EndsInPast {
            get {
                return ResourceManager.GetString("Renting_EndsInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodloužení nemůže být dokončeno, protože předmět {0} bude v tuto dobu vypůjčen..
        /// </summary>
        public static string Renting_ExtendUnavaible {
            get {
                return ResourceManager.GetString("Renting_ExtendUnavaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některý z vypůjčených předmětů neexistuje..
        /// </summary>
        public static string Renting_ItemNotFound {
            get {
                return ResourceManager.GetString("Renting_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předměty (pouze dostupné v zadanou dobu).
        /// </summary>
        public static string Renting_Items {
            get {
                return ResourceManager.GetString("Renting_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět {0} nemůže být vypůjčen od {1} do {2}, protože je již zapůjčený..
        /// </summary>
        public static string Renting_ItemUnavaible {
            get {
                return ResourceManager.GetString("Renting_ItemUnavaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neexistující zákazník si nemůže nice vypůjčit..
        /// </summary>
        public static string Renting_NoCustomer {
            get {
                return ResourceManager.GetString("Renting_NoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčku, která již skončila nelze upravit.
        /// </summary>
        public static string Renting_NoEdit {
            get {
                return ResourceManager.GetString("Renting_NoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro výpůjčku nebyl vybrán žádný předmět..
        /// </summary>
        public static string Renting_NoItem {
            get {
                return ResourceManager.GetString("Renting_NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snažíte si vypůjčit předmět z neexistující půjčovny. .
        /// </summary>
        public static string Renting_NoRental {
            get {
                return ResourceManager.GetString("Renting_NoRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snažíte se editovat neexistující výpůjčku..
        /// </summary>
        public static string Renting_NoRenting {
            get {
                return ResourceManager.GetString("Renting_NoRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Renting_Note {
            get {
                return ResourceManager.GetString("Renting_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět {0} není z této půjčovny..
        /// </summary>
        public static string Renting_NotValidItem {
            get {
                return ResourceManager.GetString("Renting_NotValidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek výpůjčky.
        /// </summary>
        public static string Renting_StartsAt {
            get {
                return ResourceManager.GetString("Renting_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek výpůjčky musí být v pracovní době..
        /// </summary>
        public static string Renting_StartsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_StartsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav výpůjčky.
        /// </summary>
        public static string Renting_State {
            get {
                return ResourceManager.GetString("Renting_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže končit dřív než začíná.
        /// </summary>
        public static string Renting_WrongDate {
            get {
                return ResourceManager.GetString("Renting_WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled.
        /// </summary>
        public static string RentingOverview {
            get {
                return ResourceManager.GetString("RentingOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete zákazníkovi &quot;{0}&quot; zrušít výpůjčku ?.
        /// </summary>
        public static string RentingOverView_CancelConfrim {
            get {
                return ResourceManager.GetString("RentingOverView_CancelConfrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změny nebyly dokončeny, dejte F5 a zkuste to znovu..
        /// </summary>
        public static string RentingOverview_CannotChangeState {
            get {
                return ResourceManager.GetString("RentingOverview_CannotChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označit výpůjčku jako.
        /// </summary>
        public static string RentingOverView_MarkAs {
            get {
                return ResourceManager.GetString("RentingOverView_MarkAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypůjčenou.
        /// </summary>
        public static string RentingOverView_MarkAsLended {
            get {
                return ResourceManager.GetString("RentingOverView_MarkAsLended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navrácenou.
        /// </summary>
        public static string RentingOverView_MarkAsReturned {
            get {
                return ResourceManager.GetString("RentingOverView_MarkAsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenavrácené výpůjčky.
        /// </summary>
        public static string RentingOverview_NonReturned {
            get {
                return ResourceManager.GetString("RentingOverview_NonReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné takové výpůjčky nejsou.
        /// </summary>
        public static string RentingOverview_NoRenting {
            get {
                return ResourceManager.GetString("RentingOverview_NoRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhající výpůjčky.
        /// </summary>
        public static string RentingOverview_OnGoing {
            get {
                return ResourceManager.GetString("RentingOverview_OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snažíte se označit výpůjčku, která již skončila jako vypůjčenou..
        /// </summary>
        public static string RentingOverView_RentingInPast {
            get {
                return ResourceManager.GetString("RentingOverView_RentingInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka již skončila.
        /// </summary>
        public static string RentingOverView_RentingInPastHeader {
            get {
                return ResourceManager.GetString("RentingOverView_RentingInPastHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejete si přidat záznam do historie k některému z předmětů ?.
        /// </summary>
        public static string RentingOverView_RentingReturned {
            get {
                return ResourceManager.GetString("RentingOverView_RentingReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navrácení výpůjčky.
        /// </summary>
        public static string RentingOverView_RentingReturnedHeader {
            get {
                return ResourceManager.GetString("RentingOverView_RentingReturnedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnes navrácené výpůjčky.
        /// </summary>
        public static string RentingOverview_Returned {
            get {
                return ResourceManager.GetString("RentingOverview_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypůjčeno.
        /// </summary>
        public static string RentingOverview_SetLended {
            get {
                return ResourceManager.GetString("RentingOverview_SetLended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navráceno.
        /// </summary>
        public static string RentingOverview_SetReturned {
            get {
                return ResourceManager.GetString("RentingOverview_SetReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčky startující dnes.
        /// </summary>
        public static string RentingOverview_StartingToday {
            get {
                return ResourceManager.GetString("RentingOverview_StartingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčky, které budou navráceny.
        /// </summary>
        public static string RentingOverview_ToBeReturned {
            get {
                return ResourceManager.GetString("RentingOverview_ToBeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled dnešních výpůjček.
        /// </summary>
        public static string RentingOverview_Today {
            get {
                return ResourceManager.GetString("RentingOverview_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
