//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Web.Localization.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit a přidat předmět.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový.
        /// </summary>
        public static string AddNewItemType {
            get {
                return ResourceManager.GetString("AddNewItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendář.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit všechny obrázky.
        /// </summary>
        public static string ChangeAllImages {
            get {
                return ResourceManager.GetString("ChangeAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhledový obrázek.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejdříve vytvořte půjčovnu.
        /// </summary>
        public static string CreateFirst {
            get {
                return ResourceManager.GetString("CreateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová výpůjčka.
        /// </summary>
        public static string CreateRenting {
            get {
                return ResourceManager.GetString("CreateRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit typ.
        /// </summary>
        public static string CreateType {
            get {
                return ResourceManager.GetString("CreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazníci.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takto je uvidí vaši zákazníci.
        /// </summary>
        public static string CustomersView {
            get {
                return ResourceManager.GetString("CustomersView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat předmět &quot;{0}&quot;.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisek.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail předmětu {0}.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editovat.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace předmětu.
        /// </summary>
        public static string EditItemType {
            get {
                return ResourceManager.GetString("EditItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace půjčovny.
        /// </summary>
        public static string EditRental {
            get {
                return ResourceManager.GetString("EditRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaměstnanci.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek úspěšně změněn.
        /// </summary>
        public static string FileChanged {
            get {
                return ResourceManager.GetString("FileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor úspěšně nahrán.
        /// </summary>
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor se nepodařilo nahrát, zkotrolujte zda nahráváte obrázek a zkuste to znovu..
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název předmětu.
        /// </summary>
        public static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předměty.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled předmětů.
        /// </summary>
        public static string ItemTypes {
            get {
                return ResourceManager.GetString("ItemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam fyzických předmětů.
        /// </summary>
        public static string ListOfItems {
            get {
                return ResourceManager.GetString("ListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesprávné přihlašovací jméno nebo heslo..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení z administrativy proběhlo úspěšně..
        /// </summary>
        public static string LogoutSuccesful {
            get {
                return ResourceManager.GetString("LogoutSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet předmětů: {0}.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet předmětů.
        /// </summary>
        public static string NumberOfItemsLabel {
            get {
                return ResourceManager.GetString("NumberOfItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamatovat si mě?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Půjčovna.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string Rental_City {
            get {
                return ResourceManager.GetString("Rental_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavírá.
        /// </summary>
        public static string Rental_EndsAt {
            get {
                return ResourceManager.GetString("Rental_EndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimální časový úsek pro výpůjčku (v minutách).
        /// </summary>
        public static string Rental_MinTimeUnit {
            get {
                return ResourceManager.GetString("Rental_MinTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název půjčovny.
        /// </summary>
        public static string Rental_Name {
            get {
                return ResourceManager.GetString("Rental_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemůžete zavírat dříve než otvíráte.
        /// </summary>
        public static string Rental_OpeningHoursError {
            get {
                return ResourceManager.GetString("Rental_OpeningHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevírá.
        /// </summary>
        public static string Rental_StartsAt {
            get {
                return ResourceManager.GetString("Rental_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Rental_Street {
            get {
                return ResourceManager.GetString("Rental_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string Rental_ZipCode {
            get {
                return ResourceManager.GetString("Rental_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat předměty.
        /// </summary>
        public static string Renting_ChooseItems {
            get {
                return ResourceManager.GetString("Renting_ChooseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová výpůjčka.
        /// </summary>
        public static string Renting_Create {
            get {
                return ResourceManager.GetString("Renting_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník.
        /// </summary>
        public static string Renting_Customer {
            get {
                return ResourceManager.GetString("Renting_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže být v minulosti.
        /// </summary>
        public static string Renting_DateInPast {
            get {
                return ResourceManager.GetString("Renting_DateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec výpůjčky.
        /// </summary>
        public static string Renting_EndsAt {
            get {
                return ResourceManager.GetString("Renting_EndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec výpůjčky musí být v pracovní době..
        /// </summary>
        public static string Renting_EndsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_EndsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže končit v minulosti, pokud není vrácena..
        /// </summary>
        public static string Renting_EndsInPast {
            get {
                return ResourceManager.GetString("Renting_EndsInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některý z vypůjčených předmětů neexistuje..
        /// </summary>
        public static string Renting_ItemNotFound {
            get {
                return ResourceManager.GetString("Renting_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předměty (pouze dostupné v zadanou dobu).
        /// </summary>
        public static string Renting_Items {
            get {
                return ResourceManager.GetString("Renting_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět {0} nemůže být vypůjčen od {1} do {2}, protože je již zapůjčený..
        /// </summary>
        public static string Renting_ItemUnavaible {
            get {
                return ResourceManager.GetString("Renting_ItemUnavaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neexistující zákazník si nemůže nice vypůjčit..
        /// </summary>
        public static string Renting_NoCustomer {
            get {
                return ResourceManager.GetString("Renting_NoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro výpůjčku nebyl vybrán žádný předmět..
        /// </summary>
        public static string Renting_NoItem {
            get {
                return ResourceManager.GetString("Renting_NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snažíte si vypůjčit předmět z neexistující půjčovny. .
        /// </summary>
        public static string Renting_NoRental {
            get {
                return ResourceManager.GetString("Renting_NoRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Renting_Note {
            get {
                return ResourceManager.GetString("Renting_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět {0} není z této půjčovny..
        /// </summary>
        public static string Renting_NotValidItem {
            get {
                return ResourceManager.GetString("Renting_NotValidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek výpůjčky.
        /// </summary>
        public static string Renting_StartsAt {
            get {
                return ResourceManager.GetString("Renting_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek výpůjčky musí být v pracovní době..
        /// </summary>
        public static string Renting_StartsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_StartsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav výpůjčky.
        /// </summary>
        public static string Renting_State {
            get {
                return ResourceManager.GetString("Renting_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nemůže končit dřív než začíná.
        /// </summary>
        public static string Renting_WrongDate {
            get {
                return ResourceManager.GetString("Renting_WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled.
        /// </summary>
        public static string RentingOverview {
            get {
                return ResourceManager.GetString("RentingOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit výpůjčku.
        /// </summary>
        public static string RentingOverview_Cancel {
            get {
                return ResourceManager.GetString("RentingOverview_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změny nebyly dokončeny, dejte F5 a zkuste to znovu..
        /// </summary>
        public static string RentingOverview_CannotChangeState {
            get {
                return ResourceManager.GetString("RentingOverview_CannotChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenavrácené výpůjčky.
        /// </summary>
        public static string RentingOverview_NonReturned {
            get {
                return ResourceManager.GetString("RentingOverview_NonReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné takové výpůjčky nejsou.
        /// </summary>
        public static string RentingOverview_NoRenting {
            get {
                return ResourceManager.GetString("RentingOverview_NoRenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhající výpůjčky.
        /// </summary>
        public static string RentingOverview_OnGoing {
            get {
                return ResourceManager.GetString("RentingOverview_OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnes navrácené výpůjčky.
        /// </summary>
        public static string RentingOverview_Returned {
            get {
                return ResourceManager.GetString("RentingOverview_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypůjčeno.
        /// </summary>
        public static string RentingOverview_SetLended {
            get {
                return ResourceManager.GetString("RentingOverview_SetLended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navráceno.
        /// </summary>
        public static string RentingOverview_SetReturned {
            get {
                return ResourceManager.GetString("RentingOverview_SetReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčky startující dnes.
        /// </summary>
        public static string RentingOverview_StartingToday {
            get {
                return ResourceManager.GetString("RentingOverview_StartingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčky, které budou navráceny.
        /// </summary>
        public static string RentingOverview_ToBeReturned {
            get {
                return ResourceManager.GetString("RentingOverview_ToBeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled dnešních výpůjček.
        /// </summary>
        public static string RentingOverview_Today {
            get {
                return ResourceManager.GetString("RentingOverview_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dva nebo více předmětů nemůže mít stejné unikatní identifikátory.
        /// </summary>
        public static string SameUniqueIdentifiers1 {
            get {
                return ResourceManager.GetString("SameUniqueIdentifiers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikátní klíč &quot;{0}&quot; nemůže být použit, protože již náleží jinému předmětu.
        /// </summary>
        public static string SameUniqueIdentifiers2 {
            get {
                return ResourceManager.GetString("SameUniqueIdentifiers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikátní identifikátor.
        /// </summary>
        public static string UniqueIdentifier {
            get {
                return ResourceManager.GetString("UniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát soubor.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít místní přihlášení.
        /// </summary>
        public static string UseAdminAccount {
            get {
                return ResourceManager.GetString("UseAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít externí služby.
        /// </summary>
        public static string UseExternalLogin {
            get {
                return ResourceManager.GetString("UseExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
