//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Web.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Košík.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypůjčit.
        /// </summary>
        public static string Basket_Rent {
            get {
                return ResourceManager.GetString("Basket_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příslušenství.
        /// </summary>
        public static string ItemDetail_Accessories {
            get {
                return ResourceManager.GetString("ItemDetail_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat do košíku.
        /// </summary>
        public static string ItemDetail_AddToCart {
            get {
                return ResourceManager.GetString("ItemDetail_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit v košíku.
        /// </summary>
        public static string ItemDetail_ChangeCart {
            get {
                return ResourceManager.GetString("ItemDetail_ChangeCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet předmětů k vypůjčení.
        /// </summary>
        public static string ItemDetail_NumberOfItems {
            get {
                return ResourceManager.GetString("ItemDetail_NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat z košíku.
        /// </summary>
        public static string ItemDetail_RemoveFromCart {
            get {
                return ResourceManager.GetString("ItemDetail_RemoveFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Časová dostupnost.
        /// </summary>
        public static string ItemDetail_TimeAvaibility {
            get {
                return ResourceManager.GetString("ItemDetail_TimeAvaibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Závisí na vámi zvoleném počtu předmětů.
        /// </summary>
        public static string ItemDetail_TimeDependant {
            get {
                return ResourceManager.GetString("ItemDetail_TimeDependant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupné od.
        /// </summary>
        public static string ItemOverview_AvaibleFrom {
            get {
                return ResourceManager.GetString("ItemOverview_AvaibleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít filtry.
        /// </summary>
        public static string ItemOverview_UseFilters {
            get {
                return ResourceManager.GetString("ItemOverview_UseFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsah košíku.
        /// </summary>
        public static string Renting_Basket {
            get {
                return ResourceManager.GetString("Renting_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesmí být v minulosti.
        /// </summary>
        public static string Renting_DateInPast {
            get {
                return ResourceManager.GetString("Renting_DateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec výpůjčky.
        /// </summary>
        public static string Renting_EndsAt {
            get {
                return ResourceManager.GetString("Renting_EndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nesmí končit mimo pracovní dobu.
        /// </summary>
        public static string Renting_EndsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_EndsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět {0} není v danou dobu dostupný..
        /// </summary>
        public static string Renting_ItemNotAvaible {
            get {
                return ResourceManager.GetString("Renting_ItemNotAvaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od předmětu {0} je v danou dobu dostupno jenom {1} kusů..
        /// </summary>
        public static string Renting_ItemsNotAvaible {
            get {
                return ResourceManager.GetString("Renting_ItemsNotAvaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezena půjčovna.
        /// </summary>
        public static string Renting_NoRental {
            get {
                return ResourceManager.GetString("Renting_NoRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Košík je prázdný.
        /// </summary>
        public static string Renting_NothingInBasket {
            get {
                return ResourceManager.GetString("Renting_NothingInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vámi vypůjčené předměty si můžete vyzvednou na adrese:.
        /// </summary>
        public static string Renting_PickUp {
            get {
                return ResourceManager.GetString("Renting_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek výpůjčky.
        /// </summary>
        public static string Renting_StartsAt {
            get {
                return ResourceManager.GetString("Renting_StartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčka nesmí začínat mimo pracovní dobu.
        /// </summary>
        public static string Renting_StartsAtNotInWorkingHours {
            get {
                return ResourceManager.GetString("Renting_StartsAtNotInWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpůjčení proběhlo v pořádku.
        /// </summary>
        public static string Renting_Success {
            get {
                return ResourceManager.GetString("Renting_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bude vypůjčeno {0} kusů.
        /// </summary>
        public static string Renting_WillBerented {
            get {
                return ResourceManager.GetString("Renting_WillBerented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesmí končit dřív než začíná.
        /// </summary>
        public static string Renting_WrongDate {
            get {
                return ResourceManager.GetString("Renting_WrongDate", resourceCulture);
            }
        }
    }
}
